import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
const enc=new TextEncoder();
const hex=(b:ArrayBuffer|Uint8Array)=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
const sha=async(s:string)=>hex(await crypto.subtle.digest('SHA-256',enc.encode(s)));
const hmac=async(key:Uint8Array,msg:string)=>new Uint8Array(await crypto.subtle.sign('HMAC',await crypto.subtle.importKey('raw',key,{name:'HMAC',hash:'SHA-256'},false,['sign']),enc.encode(msg)));
const esc=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const fmtDate=(iso:string)=>{const d=new Date(iso+'T12:00:00Z');const w=['Søndag','Mandag','Tirsdag','Onsdag','Torsdag','Fredag','Lørdag'];const m=['januar','februar','marts','april','maj','juni','juli','august','september','oktober','november','december'];return `${w[d.getUTCDay()]} d. ${d.getUTCDate()}. ${m[d.getUTCMonth()]} ${d.getUTCFullYear()}`};
async function sendSes(to:string,subject:string,html:string){
 const access=Deno.env.get('AWS_ACCESS_KEY_ID'),secret=Deno.env.get('AWS_SECRET_ACCESS_KEY'),session=Deno.env.get('AWS_SESSION_TOKEN');if(!access||!secret)throw new Error('SES_CREDENTIALS_MISSING');
 const region=Deno.env.get('AWS_SES_REGION')||'eu-north-1',from=Deno.env.get('AWS_SES_FROM')||'Morgentidende <nyhedsbrev@morgentidende.dk>',host=`email.${region}.amazonaws.com`,path='/v2/email/outbound-emails';
 const payload=JSON.stringify({FromEmailAddress:from,Destination:{ToAddresses:[to]},Content:{Simple:{Subject:{Data:subject,Charset:'UTF-8'},Body:{Html:{Data:html,Charset:'UTF-8'}}}}});
 const now=new Date().toISOString().replace(/[:-]|\.\d{3}/g,''),day=now.slice(0,8),payloadHash=await sha(payload),extra=session?`x-amz-security-token:${session}\n`:'',signed=session?'content-type;host;x-amz-date;x-amz-security-token':'content-type;host;x-amz-date';
 const headers=`content-type:application/json\nhost:${host}\nx-amz-date:${now}\n${extra}`,canonical=`POST\n${path}\n\n${headers}\n${signed}\n${payloadHash}`,scope=`${day}/${region}/ses/aws4_request`,sts=`AWS4-HMAC-SHA256\n${now}\n${scope}\n${await sha(canonical)}`;
 let k=await hmac(enc.encode('AWS4'+secret),day);k=await hmac(k,region);k=await hmac(k,'ses');k=await hmac(k,'aws4_request');const sig=hex(await crypto.subtle.sign('HMAC',await crypto.subtle.importKey('raw',k,{name:'HMAC',hash:'SHA-256'},false,['sign']),enc.encode(sts)));
 const h:Record<string,string>={'content-type':'application/json','x-amz-date':now,authorization:`AWS4-HMAC-SHA256 Credential=${access}/${scope}, SignedHeaders=${signed}, Signature=${sig}`};if(session)h['x-amz-security-token']=session;
 const r=await fetch(`https://${host}${path}`,{method:'POST',headers:h,body:payload});if(!r.ok)throw new Error(`SES_${r.status}_${(await r.text()).slice(0,200)}`);
}
function html(articles:any[],date:string){
 const bg='#f4efe5',card='#fffaf2',head='#182534',body='#535862',muted='#6f7178',border='#e6ddcf';
 const items=articles.map((a,i)=>{const u=`https://morgentidende.dk/artikel/${encodeURIComponent(a.slug)}`;return i===0?`<tr><td style="padding:30px 0 32px;border-top:1px solid ${border};border-bottom:1px solid ${border}"><div style="margin:0 0 10px;color:#b17b16;font-size:11px;font-weight:800;letter-spacing:1.8px;text-transform:uppercase">Tophistorie</div><a href="${u}" style="font-family:Georgia,serif;font-size:31px;line-height:1.12;font-weight:700;color:${head};text-decoration:none">${esc(a.headline)}</a>${a.deck?`<p style="margin:12px 0 0;font-size:16px;line-height:1.6;color:${body}">${esc(a.deck)}</p>`:''}<div style="margin-top:16px"><a href="${u}" style="font-size:13px;font-weight:700;color:#b17b16;text-decoration:none">Læs historien →</a></div></td></tr>`:`<tr><td style="padding:24px 0;border-bottom:1px solid ${border}"><a href="${u}" style="font-family:Georgia,serif;font-size:22px;line-height:1.22;font-weight:700;color:${head};text-decoration:none">${esc(a.headline)}</a>${a.deck?`<p style="margin:9px 0 0;font-size:15px;line-height:1.58;color:${body}">${esc(a.deck)}</p>`:''}</td></tr>`}).join('');
 return `<!doctype html><html lang="da"><body style="margin:0;background:${bg};font-family:Arial,Helvetica,sans-serif"><table width="100%" role="presentation" cellspacing="0" cellpadding="0" style="background:${bg};padding:26px 12px"><tr><td align="center"><table width="100%" role="presentation" cellspacing="0" cellpadding="0" style="max-width:680px;background:${card};border:1px solid ${border}"><tr><td style="padding:28px 38px;background:#182534;color:#fffaf0;text-align:center;border-top:4px solid #d8a33d"><div style="font-size:42px;line-height:1;color:#e9bf64">☀</div><div style="font-family:Georgia,serif;font-size:34px;font-weight:700">Morgentidende</div><div style="margin-top:10px;color:#e9bf64;font-size:11px;font-weight:800;letter-spacing:1.5px">TEST · MORGENOVERBLIK · ${esc(fmtDate(date)).toUpperCase()}</div></td></tr><tr><td style="padding:34px 40px 16px"><h1 style="margin:0 0 7px;font-family:Georgia,serif;font-size:31px;color:${head}">Døgnets 6 stærkeste historier</h1><p style="margin:0 0 18px;color:${muted};font-size:14px">Med særligt blik for væsentlige historier, der har fyldt mindre i danske medier.</p><table width="100%" role="presentation" cellspacing="0" cellpadding="0">${items}</table></td></tr><tr><td style="padding:20px 40px 28px;border-top:1px solid ${border};color:${muted};font-size:12px">TESTMAIL · påvirker ikke den automatiske morgenudsendelse.</td></tr></table></td></tr></table></body></html>`;
}
const cors={'access-control-allow-origin':'https://morgentidende.dk','access-control-allow-headers':'content-type','access-control-allow-methods':'POST,OPTIONS','content-type':'application/json'};
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return new Response(JSON.stringify({error:'METHOD_NOT_ALLOWED'}),{status:405,headers:cors});
 try{const b=await req.json(),email=String(b.email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return new Response(JSON.stringify({error:'INVALID_EMAIL'}),{status:400,headers:cors});
 const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
 const {data:allowed}=await db.from('v5_newsletter_subscribers').select('email').eq('email',email).maybeSingle();if(!allowed)return new Response(JSON.stringify({error:'TEST_RECIPIENT_NOT_REGISTERED'}),{status:403,headers:cors});
 const {data,error}=await db.from('v5_articles').select('slug,headline,deck,published_at,frontpage_destination,is_breaking,article_kind').neq('article_kind','magazine').order('is_breaking',{ascending:false}).order('published_at',{ascending:false}).limit(20);if(error)throw error;
 const articles=(data||[]).sort((a:any,b:any)=>((b.frontpage_destination==='lead'?2:0)-(a.frontpage_destination==='lead'?2:0))||(+new Date(b.published_at)-+new Date(a.published_at))).slice(0,6);if(!articles.length)return new Response(JSON.stringify({error:'NO_ARTICLES'}),{status:409,headers:cors});
 const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Copenhagen'}).format(new Date());await sendSes(email,'[TEST] Morgentidende – døgnets 6 stærkeste historier',html(articles,date));return new Response(JSON.stringify({ok:true,articles:articles.length}),{status:200,headers:cors});
 }catch(e){console.error(e);return new Response(JSON.stringify({error:'TEST_SEND_FAILED'}),{status:500,headers:cors})}});
